name: booking_app
description: Flutter Booking App

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  http: ^0.13.5
  logging: ^1.1.0
  shared_preferences: ^2.0.15
  auto_route: ^5.0.2
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-Medium.otf
        - asset: assets/fonts/Poppins-SemiBold.otf
        - asset: assets/fonts/Poppins-Bold.otf
        - asset: assets/fonts/Poppins-ExtraBold.otf
        - asset: assets/fonts/Poppins-Black.otf
